name: algolia doc-search
on:
  - push
jobs:
  check:
    name: Check changed docs files
    outputs:
      run-scrape-docs-job: ${{ steps.check_files.outputs.run_scrape_docs_job }}
      run-scrape-learn-job: ${{ steps.check_files.outputs.run_scrape_learn_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: dorny/paths-filter@v2.2.1
        id: check_files
        with:
          filters: |
            docs:
              - 'site/content/docs/**/*.*'
            learn:
              - 'site/content/learn/**/*.*'
  scrape-docs:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ steps.check_files.outputs.docs == 'true' }} && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Run doc-search
        uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
          file: 'algolia/config-docs.json'
  scrape-learn:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ steps.check_files.outputs.learn == 'true' }} && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Run learn-search
        uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
          file: 'algolia/config-learn.json'
